name       : gnubg
version    : 1.05.002
release    : 2
source     :
    - http://files.gnubg.org/media/sources/gnubg-release-1.05.002-sources.tar.gz : b2c5f9457a023a229708bb788aee6f712428c911e199f32fb07f3a83d6c8b60b
license    : GPL-3.0
component  : games.strategy
summary    : GNU Backgammon (gnubg) is for playing and analysing backgammon positions, games and matches.
description: |
    GNU Backgammon (gnubg) is for playing and analysing backgammon positions, games and matches.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpng)
    - pkgconfig(pangocairo)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-cputest \
            --enable-simd=sse2
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/gnubg.desktop $installdir/usr/share/applications/gnupg.desktop
