name       : gnubg
version    : 1.06.002
release    : 6
source     :
    - ftp://ftp.gnu.org/gnu/gnubg/gnubg-release-1.06.002-sources.tar.gz : ce1b0b0c1900717cc598032a14cf8c0ee60faf24d84368b39922c0102983bc87
homepage   : https://www.gnu.org/software/gnubg/
license    : GPL-3.0-or-later
component  : games.strategy
summary    : GNU Backgammon (gnubg) is for playing and analysing backgammon positions, games and matches
description: |
    GNU Backgammon (GNUbg) plays and analyzes backgammon games and matches. It is able to play and analyze both money games and tournament matches, evaluate and roll out positions, and more. 
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libcanberra)
    - pkgconfig(libpng)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-cputest \
               --enable-simd=sse2 \
               --with-gtk3 \
               --with-python=python3 \
               --without-board3d
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/gnubg.desktop $installdir/usr/share/applications/gnupg.desktop
