name       : gnubg
version    : 1.07.001
release    : 10
source     :
    - ftp://ftp.gnu.org/gnu/gnubg/gnubg-release-1.07.001-sources.tar.gz : 72399729419cad9f112c3066a12d0000da450a456add7b094d89155069d6821e
homepage   : https://www.gnu.org/software/gnubg/
license    : GPL-3.0-or-later
component  : games.strategy
summary    : GNU Backgammon (gnubg) is for playing and analysing backgammon positions, games and matches
description: |
    GNU Backgammon (GNUbg) plays and analyzes backgammon games and matches. It is able to play and analyze both money games and tournament matches, evaluate and roll out positions, and more. 
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libcanberra)
    - pkgconfig(libpng)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
setup      : |
    PYTHONWARNINGS=ignore %configure \
        --disable-cputest \
        --enable-simd=sse2 \
        --with-gtk3 \
        --with-python=python3 \
        --without-board3d
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/gnubg.desktop $installdir/usr/share/applications/gnupg.desktop
