name       : gnubg
version    : 1.06.002
release    : 4
source     :
    - http://files.gnubg.org/media/sources/gnubg-release-1.06.002-sources.tar.gz : ce1b0b0c1900717cc598032a14cf8c0ee60faf24d84368b39922c0102983bc87
license    : GPL-3.0-or-later
component  : games.strategy
summary    : GNU Backgammon (gnubg) is for playing and analysing backgammon positions, games and matches.
description: |
    GNU Backgammon (gnubg) is for playing and analysing backgammon positions, games and matches.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libpng)
    - pkgconfig(pangocairo)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-cputest \
               --enable-simd=sse2 \
               --with-gtk3 \
               --without-board3d
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/gnubg.desktop $installdir/usr/share/applications/gnupg.desktop
